### ISSUE TITLE
Error when run demo

### ISSUE THREAD

**Issue by binhmuc** [yuanyuanli85/FashionAI_KeyPoint_Detection_Challenge_Keras#6]
I got this error when i run "python2 demo.py --modelfile ../../trained_models/fashion_ai_keypoint_weights_epoch28.hdf5 --gpuID 2"

OpenCV Error: Assertion failed (cn <= 4 && ssize.area() > 0) in remapBilinear, file /build/opencv-ys8xiq/opencv-2.4.9.1+dfsg/modules/imgproc/src/imgwarp.cpp, line 2435

**Comment by binhmuc** [comment]
Can you give me the verison of opencv and tensorflow ?

**Comment by yuanyuanli85** [comment]
To run this demo, need to have dataset downloaded.  From the posted error, looks like the images are not valid.

**Comment by binhmuc** [comment]
I use the data for test in dataset  with hte size is (512,512,3).
Anyway, can you give me the version of opencv and tensorflow ?

**Comment by yuanyuanli85** [comment]
opencv: 3.4.0 
tensorflow: 1.8.0

**Comment by binhmuc** [comment]
Thanks you.
